version: '3.1'
services:
  db:
    image: mysql
    container_name: distprog-finance
    environment:
      MYSQL_ROOT_PASSWORD: root
      #To map for another port
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - distprog-finance:/var/lib/mysql

volumes:
  distprog-finance:
